[node]
# working_dir = "/home/greg/hc-space"
rpc_bind = "0.0.0.0:30443"
p2p_bind = "0.0.0.0:30444"
mining_key = "6e14c883fb38097e0eecdcad9d498c1086d5c038a138f56ad512811512b604df01"
miner = true
wait_time_for_microblocks = 0
wait_before_first_anchored_block = 0

[[events_observer]]
endpoint = "localhost:60304"
retry_count = 255
events_keys = ["*"]

[miner]
first_attempt_time_ms = 30_000
subsequent_attempt_time_ms = 1_000
microblock_attempt_time_ms = 1_000

[burnchain]
chain = "stacks_layer_1"
mode = "xenon"
# chain = "mockstack"
# mode = "mainnet"
first_burn_header_height = 5
contract_identifier = "STTAKDFQ15A90V9S6NK66BZMM4X1EGMV29X73DW7.hc-alpha"
peer_host = "127.0.0.1"
rpc_port = 20443
peer_port = 20444
rpc_ssl = false

[[ustx_balance]]
address = "STFTX3F4XCY7RS5VRHXP2SED0WC0YRKNWTNXD74P"
amount = 10000000000000000

[[ustx_balance]]
address = "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM"
amount = 10000000000000000
