
[project]
name = "core-contracts"

[contracts.trait-standards]
path = "contracts/helper/trait-standards.clar"
clarity_version = 2

[contracts.simple-nft]
path = "contracts/helper/simple-nft.clar"
clarity_version = 2

[contracts.simple-nft-no-mint]
path = "contracts/helper/simple-nft-no-mint.clar"
clarity_version = 2

[contracts.second-simple-nft]
path = "contracts/helper/simple-nft.clar"
clarity_version = 2

[contracts.simple-ft]
path = "contracts/helper/simple-ft.clar"
clarity_version = 2

[contracts.second-simple-ft]
path = "contracts/helper/simple-ft.clar"
clarity_version = 2

[contracts.subnet]
path = "contracts/subnet.clar"
clarity_version = 2 
epoch = 2.1

[contracts.multi-miner]
path = "contracts/multi-miner.clar"
clarity_version = 2 
epoch = 2.1

[contracts.test-helpers]
path = "contracts/helper/test-helpers.clar"
clarity_version = 2
