
[project]
name = "core-contracts"

[contracts.trait-standards]
path = "contracts/helper/trait-standards.clar"
depends_on = []

[contracts.simple-nft]
path = "contracts/helper/simple-nft.clar"
depends_on = ["trait-standards"]

[contracts.simple-nft-no-mint]
path = "contracts/helper/simple-nft-no-mint.clar"
depends_on = ["trait-standards"]

[contracts.simple-ft]
path = "contracts/helper/simple-ft.clar"
depends_on = ["trait-standards"]

[contracts.hyperchains]
path = "contracts/hyperchains.clar"
depends_on = ["trait-standards"]
